### ISSUE TITLE
Migrate tests to slick 3.0 approach

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/beholder#34]
Tests are currently strongly dependes on session and unicorn. We need rewrite them into slick 3.0 approach.

**Comment by michalbogacz** [comment]
I created the pull request  https://github.com/VirtusLab/beholder/pull/44 for this issue.

**Comment by liosedhel** [comment]
Fixed already in version 1.1.x. Sorry @michalbogacz for confusion :/
